### ISSUE TITLE
Landing/homepage

### ISSUE THREAD

**Issue by andie28874** [TeamHealthcareSidePrjct/mentalhealth-aapi#1]
**As** an app user, **I want to** know what value the product will bring into my life **so that** I am motivated to use the product. The more motivated I am, the more persistent and patient I will be when interacting with the web app.

### Acceptance Criteria:
- [ ] **Given** that I have the landing page open on my browser, **when** I am trying to explore by scrolling down **then** the page should smoothly transition to the bottom.

![Screen Shot 2021-03-24 at 4.15.11 PM.png](https://images.zenhubusercontent.com/605ab753cc7ec8d8eae1d96d/ddf5fc88-31d7-40b3-9404-465b0459e28b)

Figma link: https://www.figma.com/file/G5SHybFhx2WmnIaq838YiI/SIDE-PRJCT-helth?node-id=309%3A0

### Assets: 
![How To Final.svg](https://images.zenhubusercontent.com/605ab753cc7ec8d8eae1d96d/a571dda4-7f2b-4804-8821-4a4489956012)![Begin Button.svg](https://images.zenhubusercontent.com/605ab753cc7ec8d8eae1d96d/fb543220-61d2-4858-9d75-047076e33d06)![Get Started.svg](https://images.zenhubusercontent.com/605ab753cc7ec8d8eae1d96d/bc340555-711e-4ccb-b32d-1a79d8057c35)![SIDE PRJCT LANDING PAGE BCKGRD 1.svg](https://images.zenhubusercontent.com/605ab753cc7ec8d8eae1d96d/48ee000a-4b53-4816-8b79-e5cc6b7e35a4)

**Comment by sunnyliu1997** [comment]
![LANDING PAGE BCKGRD.png](https://images.zenhubusercontent.com/605a9697de1f76ba88eaa2f5/aa6208a7-6415-4c18-9c1d-945a469c42f5)

**Comment by sunnyliu1997** [comment]
Asset![SIDE PRJCT LANDING PAGE BCKGRD 1.png](https://images.zenhubusercontent.com/605a9697de1f76ba88eaa2f5/7b0ba6a4-1714-4251-b0f7-0b32fe4d4677): Landing page background

**Comment by sunnyliu1997** [comment]
![SIDE PRJCT LANDING PAGE BCKGRD 1.svg](https://images.zenhubusercontent.com/605a9697de1f76ba88eaa2f5/dbce24c8-f24e-42ca-ab55-70ce1f059ad9)

**Comment by sunnyliu1997** [comment]
![Begin Button.svg](https://images.zenhubusercontent.com/605a9697de1f76ba88eaa2f5/123bddeb-8063-43cb-951b-d02f49f2349e)

**Comment by sunnyliu1997** [comment]
![Get Started.svg](https://images.zenhubusercontent.com/605a9697de1f76ba88eaa2f5/f6834b71-71f7-41f4-b1a8-08173a98ea4f)

**Comment by sunnyliu1997** [comment]
![How To.svg](https://images.zenhubusercontent.com/605a9697de1f76ba88eaa2f5/030cd792-7e06-4c4f-9df7-11c8825e2736)

**Comment by sunnyliu1997** [comment]
Figma link: https://www.figma.com/file/G5SHybFhx2WmnIaq838YiI/SIDE-PRJCT-helth?node-id=309%3A0

**Comment by sunnyliu1997** [comment]
![How To Final.svg](https://images.zenhubusercontent.com/605a9697de1f76ba88eaa2f5/a9a34165-af58-49ec-a37e-b5160435e220)
